# Generated by Django 3.1.2 on 2020-10-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('introduction', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(max_length=1000)),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('room_count', models.IntegerField()),
                ('checkin_time', models.CharField(max_length=20)),
                ('checkout_time', models.CharField(max_length=20)),
                ('x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('tel_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('description_title', models.CharField(max_length=200)),
                ('description_first', models.TextField()),
                ('description_second', models.TextField()),
                ('description_third', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.category')),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'hotel_services',
            },
        ),
        migrations.CreateModel(
            name='HotelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'hotel_tags',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('price_weekday', models.IntegerField()),
                ('price_weekend', models.IntegerField()),
                ('price_peak', models.IntegerField()),
                ('stay_at_least', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room', models.ManyToManyField(related_name='types', through='hotel.RoomType', to='hotel.Room')),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hotel', models.ManyToManyField(related_name='tags', through='hotel.HotelTag', to='hotel.Hotel')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(max_length=1000)),
                ('hotel', models.ManyToManyField(related_name='services', through='hotel.HotelService', to='hotel.Hotel')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.type'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.facility')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'db_table': 'room_facilities',
            },
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('detail_top', models.TextField()),
                ('detail_content', models.TextField()),
                ('detail_sign', models.CharField(max_length=20)),
                ('detail_sign_image', models.CharField(max_length=1000)),
                ('special1', models.CharField(max_length=20)),
                ('special1_content', models.TextField()),
                ('special2', models.CharField(max_length=20)),
                ('special2_content', models.TextField()),
                ('special3', models.CharField(max_length=20)),
                ('special3_content', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'more_infos',
            },
        ),
        migrations.CreateModel(
            name='InfoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1_name', models.CharField(max_length=40)),
                ('place1_detail', models.CharField(max_length=200)),
                ('place1_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place1_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place2_name', models.CharField(max_length=40)),
                ('place2_detail', models.CharField(max_length=200)),
                ('place2_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place2_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place3_name', models.CharField(max_length=40)),
                ('place3_detail', models.CharField(max_length=200)),
                ('place3_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place3_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place4_name', models.CharField(max_length=40)),
                ('place4_detail', models.CharField(max_length=200)),
                ('place4_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place4_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place5_name', models.CharField(max_length=40)),
                ('place5_detail', models.CharField(max_length=200)),
                ('place5_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place5_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place6_name', models.CharField(max_length=40)),
                ('place6_detail', models.CharField(max_length=200)),
                ('place6_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place6_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place7_name', models.CharField(max_length=40)),
                ('place7_detail', models.CharField(max_length=200)),
                ('place7_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place7_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place8_name', models.CharField(max_length=40)),
                ('place8_detail', models.CharField(max_length=200)),
                ('place8_x', models.DecimalField(decimal_places=7, max_digits=12)),
                ('place8_y', models.DecimalField(decimal_places=7, max_digits=12)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.moreinfo')),
            ],
            options={
                'db_table': 'info_locations',
            },
        ),
        migrations.AddField(
            model_name='hoteltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.tag'),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.service'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'hotel_images',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.location'),
        ),
        migrations.AddField(
            model_name='facility',
            name='room',
            field=models.ManyToManyField(related_name='facilities', through='hotel.RoomFacility', to='hotel.Room'),
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room', models.ManyToManyField(related_name='bed_types', through='hotel.Bed', to='hotel.Room')),
            ],
            options={
                'db_table': 'bed_types',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.bedtype'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
