# Generated by Django 3.1.2 on 2020-10-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('booking', '0002_auto_20201021_1820'),
        ('hotel', '0002_auto_20201021_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.ManyToManyField(related_name='rooms', through='booking.Booking', to='user.User'),
        ),
    ]
