# Generated by Django 3.1.2 on 2020-10-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_marketing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_privacy',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_service',
            field=models.BooleanField(null=True),
        ),
    ]
