# Generated by Django 3.1.2 on 2020-10-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201023_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_service',
            field=models.BooleanField(default=False),
        ),
    ]
